### ISSUE TITLE
File Management -> Nessus directory not found error

### ISSUE THREAD

**Issue by ethicalhack3r** [simonbt/nessus-report-parser#3]
Got a directory not found error when clicking on File Management -> Nessus from the GUI

Fixed by issuing the following command:

```sudo mkdir Library/uploads/nessus/1```

Long term fix is probably for the code to create these dirs dynamically.

**Comment by simonbt** [comment]
When you add new users it does create that file structure, but wasn't there from the initial pull for the default user. I've added it in now. Thanks!
